name: Go CI

on:
  push: 
    branches: 
      - main
      - prod
      - stage
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                go-version: 1.24
            - run: go build -v ./...
            - run: go test ./...
            - run: go vet ./...
            - run: staticcheck ./...
            - run: go fmt ./...
